# Generated by Django 4.2.5 on 2024-11-08 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardwareProject', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ProjectImage',
        ),
        migrations.AlterField(
            model_name='project',
            name='components',
            field=models.ManyToManyField(blank=True, related_name='projects', to='hardwareProject.component', verbose_name='Componente'),
        ),
    ]
