# Generated by Django 4.2.5 on 2024-11-20 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardwareProject', '0002_rename_image_projectimage_alter_project_components'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='components',
        ),
        migrations.CreateModel(
            name='ProjectComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('description', models.TextField(blank=True, max_length=400, null=True, verbose_name='Descripción')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_components', to='hardwareProject.component', verbose_name='Componente')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_components', to='hardwareProject.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Proyecto-Componente',
                'verbose_name_plural': 'Proyectos-Componentes',
                'unique_together': {('project', 'component')},
            },
        ),
    ]
